general {
    before_sleep_cmd = hyprctl dispatch dpms on && sleep 0.5 && hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on && sleep 0.5 && cat /tmp/brillo.save 2>/dev/null | xargs -r brightnessctl set
}

listener {
    timeout = 150
    on-timeout = brightnessctl get > /tmp/brillo.save && brightnessctl set 10%
    on-resume = cat /tmp/brillo.save 2>/dev/null | xargs -r brightnessctl set
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 580
    on-timeout = hyprctl dispatch dpms on && sleep 0.5 && hyprlock
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
